site_name: BeeWare
site_url: https://docs.beeware.org/
docs_dir: en

plugins:
  redirects:
    redirect_maps:
      "index.md": "https://beeware.org/docs"

theme:
  name: mkdocs
  locale: en
  custom_dir: overrides/
  static_templates:
    - 404.html
